export const CITY_CATEGORIES: Record<string, string> = {
  'Istanbul': 'Istanbul',
  'Liverpool': 'Liverpool',
  'London': 'London',
  'Paris': 'Paris',
  'New York': 'New_York_City',
  'Tokyo': 'Tokyo',
  'Berlin': 'Berlin',
  'Sydney': 'Sydney',
  'Rio': 'Rio_de_Janeiro',
  'Barcelona': 'Barcelona',
  'Rome': 'Rome',
  'Amsterdam': 'Amsterdam',
  'Hong Kong': 'Hong_Kong',
  'Los Angeles': 'Los_Angeles',
  'Chicago': 'Chicago',
  'San Francisco': 'San_Francisco',
  'Las Vegas': 'Las_Vegas',
  'Miami': 'Miami',
  'Seattle': 'Seattle',
  'Boston': 'Boston',
  'Washington DC': 'Washington,_D.C.',
  'Toronto': 'Toronto',
  'Vancouver': 'Vancouver',
  'Mexico City': 'Mexico_City',
  'Buenos Aires': 'Buenos_Aires',
  'Cape Town': 'Cape_Town',
  'Johannesburg': 'Johannesburg',
  'Nairobi': 'Nairobi',
  'Casablanca': 'Casablanca',
  'Tel Aviv': 'Tel_Aviv',
  'Delhi': 'Delhi',
  'Bangkok': 'Bangkok',
  'Jakarta': 'Jakarta',
  'Manila': 'Manila',
  'Seoul': 'Seoul',
  'Osaka': 'Osaka',
  'Kyoto': 'Kyoto',
  'Beijing': 'Beijing',
  'Shanghai': 'Shanghai',
  'Guangzhou': 'Guangzhou',
  'Shenzhen': 'Shenzhen',
  'Taipei': 'Taipei',
  'Melbourne': 'Melbourne',
  'Auckland': 'Auckland',
};

export function getSearchQueries(cityName: string): string[] {
  return [
    `${cityName} skyline`,
    `${cityName} landmark`,
    `${cityName} cityscape`,
  ];
}
